spring:

  datasource:
    url: jdbc:sqlserver://localhost;encrypt=false

  docker.compose:
    enabled: true
    file: classpath:/compose.yml
    stop:
      command: down
      timeout: 10s

  kafka:
    bootstrap-servers: localhost:29092
    security.protocol: PLAINTEXT

  rabbitmq:
    host: localhost

  sql:
    init:
      mode: always
      schema-locations: classpath:init.sql
